### ISSUE TITLE
Missing library libssl.so.1.0.0

### ISSUE THREAD

**Issue by williamccrobinson** [xataz/dockerfiles#21]
Pulling the latest image, I get the following error when attempting to run the image using previously working docker run command (this is the only output received after running the docker run command) :

`Traceback (most recent call last):
  File "/usr/certbot/venv/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/usr/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/usr/certbot/venv/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/certbot/venv/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/certbot/venv/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/certbot/venv/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/certbot/venv/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/certbot/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/certbot/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/certbot/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so)` 

When building the image myself from the Nov 7th commit of the Dockerfile, the same docker run command works as expected.

**Comment by xataz** [comment]
Can you try again with latest commit ?

XataZ

**Comment by williamccrobinson** [comment]
Great! That fixes it. Building the image from latest commit of the Dockerfile now works as expected, I was able to run it start to finish.

That was fast! Thanks for the quick response @xataz  👍
