### ISSUE TITLE
rtorrent-rutorrent : Error with filebot 

### ISSUE THREAD

**Issue by Djamy** [xataz/dockerfiles#25]
I have an error with filebot but I don't why nor who to blame. This is the error: 

```cli
cat /filebot/data/logs/amc.log
Fetch failed: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure [https://app.filebot.net/scripts/m1.jar.xz]
Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at net.filebot.web.WebRequest.fetch(WebRequest.java:143)
        at net.filebot.CachedResource.lambda$fetchIfModified$9(CachedResource.java:216)
        at net.filebot.CachedResource.lambda$null$0(CachedResource.java:87)
        at net.filebot.CachedResource.retry(CachedResource.java:120)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.retry(CachedResource.java:132)
        at net.filebot.CachedResource.lambda$get$1(CachedResource.java:87)
        at net.filebot.Cache.computeIf(Cache.java:90)
        at net.filebot.CachedResource.get(CachedResource.java:82)
        at net.filebot.MemoizedResource.get(Resource.java:36)
        at net.filebot.cli.ScriptBundle.getScript(ScriptBundle.java:32)
        at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:74)
        at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:113)
        at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:30)
        at net.filebot.Main.main(Main.java:120)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at net.filebot.web.WebRequest.fetch(WebRequest.java:140)
        ... 14 more

Failure (°_°)
```

Do you have an idea about this ?

Thanks

**Comment by ohmybside** [comment]
look like an libressl/openssl error

**Comment by Djamy** [comment]
Probably! Stil dont't know how to resolve this yet

**Comment by ohmybside** [comment]
Try to add openssl and openssl-dev in dockerfile, the last dockefile is based on alpine 3.5 and use libressl instead of openssl ! I'm not sure but maybe filebot need openssl to get info from tvdb, moviedb .etc

**Comment by Djamy** [comment]
Go idea, I'll try to rebuild with openssl and Alpine 3.4 to see if it's better or not.

Thanks.

**Comment by ohmybside** [comment]
you can also keep Alpine 3.5 just add openssl 
it's available for alpine 3.5
https://pkgs.alpinelinux.org/packages?name=openssl*&branch=v3.5&repo=&arch=x86_64&maintainer=

**Comment by Djamy** [comment]
I tried that first but I got an error. 
```cli
ERROR: unsatisfiable constraints:
  libressl-dev-2.4.4-r0:
    conflicts:
               openssl-dev-1.0.2j-r2[pc:libcrypto=2.4.4]
               openssl-dev-1.0.2j-r2[pc:libssl=2.4.4]
               openssl-dev-1.0.2j-r2[pc:openssl=2.4.4]
    satisfies: libssh2-dev-1.7.0-r2[libressl-dev]
               libssh2-dev-1.7.0-r2[pc:libcrypto]
               libssh2-dev-1.7.0-r2[pc:libssl]
               curl-dev-7.52.1-r0[libressl-dev]
  openssl-dev-1.0.2j-r2:
    conflicts:
               libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2j]
               libressl-dev-2.4.4-r0[pc:libssl=1.0.2j]
               libressl-dev-2.4.4-r0[pc:openssl=1.0.2j]
    satisfies: world[openssl-dev]
               libssh2-dev-1.7.0-r2[pc:libcrypto]
               libssh2-dev-1.7.0-r2[pc:libssl]
```

So I'm building it with Alpine 3.4 to see if I can get filebot back

**Comment by Djamy** [comment]
Filebot works with Alpine 3.4 and openssl !

I can't build with Alpine 3.5 + openssl and libressl trigger an error with Java.
So I think the issue can remain open.

Thanks @ohmybside for pointing me the problem.

**Comment by xataz** [comment]
It's good now.
I replaced openjdk8-jre-8.111.14-r1 (from alpine:3.5) by openjdk8-jre-8.111.14-r0 (from alpine:3.4), no java error with filebot.
I will contact the maintainer of openjdk to know that they are the made changes between these two versions.

**Comment by Djamy** [comment]
Great! Thank you very much :heart:

**Comment by xataz** [comment]
Issue alpine : 
https://bugs.alpinelinux.org/issues/6704
and 
https://bugs.alpinelinux.org/issues/6809

**Comment by xataz** [comment]
It works with latest version of openjdk.

I close this issue
